import { Controller, Get } from "@nestjs/common";

@Controller("keywords")
export class KeywordsController {
  private readonly KEYWORDS = [
    ".NET",
    "ASP.NET",
    "MVC",
    "Razor",
    "Blazor",
    "C#",
    "F#",
    "VB.NET",
    "Java",
    "Spring",
    "Spring Boot",
    "Jakarta EE",
    "Kotlin",
    "Scala",
    "Groovy",
    "Python",
    "Django",
    "Flask",
    "FastAPI",
    "Pyramid",
    "Ruby",
    "Rails",
    "Sinatra",
    "Node.js",
    "Express",
    "NestJS",
    "Hapi",
    "Koa",
    "JavaScript",
    "Vanilla JavaScript",
    "TypeScript",
    "Angular",
    "React",
    "Vue",
    "Svelte",
    "Ember",
    "Preact",
    "Next.js",
    "Nuxt",
    "Gatsby",
    "Rollup",
    "Webpack",
    "Vite",
    "HTML",
    "CSS",
    "Sass",
    "Less",
    "PostCSS",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Chakra UI",
    "Semantic UI",
    "Bulma",
    "GraphQL",
    "Apollo",
    "Relay",
    "REST",
    "gRPC",
    "Protocol Buffers",
    "JSON",
    "XML",
    "YAML",
    "SQL",
    "MySQL",
    "PostgreSQL",
    "SQLite",
    "MariaDB",
    "MSSQL",
    "Oracle",
    "NoSQL",
    "MongoDB",
    "Cassandra",
    "Redis",
    "DynamoDB",
    "CouchDB",
    "Firebase",
    "Elasticsearch",
    "TimescaleDB",
    "InfluxDB",
    "CockroachDB",
    "Prisma",
    "TypeORM",
    "Sequelize",
    "Entity Framework",
    "Hibernate",
    "Docker",
    "Kubernetes",
    "Helm",
    "OpenShift",
    "Docker Compose",
    "Podman",
    "Serverless",
    "AWS",
    "Azure",
    "Google Cloud",
    "GCP",
    "Azure DevOps",
    "CloudFormation",
    "Terraform",
    "Pulumi",
    "Ansible",
    "Chef",
    "Puppet",
    "CI/CD",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI",
    "CircleCI",
    "Travis CI",
    "Bash",
    "PowerShell",
    "Zsh",
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "Mercurial",
    "SVN",
    "Nginx",
    "Apache",
    "IIS",
    "Load Balancer",
    "CDN",
    "Redis Streams",
    "RabbitMQ",
    "Kafka",
    "ActiveMQ",
    "ZeroMQ",
    "gRPC",
    "WebSockets",
    "Socket.IO",
    "OAuth",
    "OpenID Connect",
    "JWT",
    "SAML",
    "LDAP",
    "IdentityServer",
    "Keycloak",
    "Security",
    "OWASP",
    "Penetration Testing",
    "Encryption",
    "TLS",
    "HTTPS",
    "CIAM",
    "Accessibility",
    "WCAG",
    "SEO",
    "Mobile",
    "iOS",
    "Android",
    "React Native",
    "Flutter",
    "Xamarin",
    "Ionic",
    "Mobile Development",
    "Embedded",
    "C",
    "C++",
    "Rust",
    "Go",
    "Perl",
    "PHP",
    "Laravel",
    "Symfony",
    "WordPress",
    "Drupal",
    "Joomla",
    "Content Management",
    "CMS",
    "Data Science",
    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "scikit-learn",
    "pandas",
    "NumPy",
    "Matplotlib",
    "Jupyter",
    "R",
    "Hadoop",
    "Spark",
    "Airflow",
    "ETL",
    "Big Data",
    "HBase",
    "Hive",
    "Kafka Streams",
    "Observability",
    "Prometheus",
    "Grafana",
    "ELK",
    "Logstash",
    "Kibana",
    "Datadog",
    "New Relic",
    "Sentry",
    "Monitoring",
    "Tracing",
    "OpenTelemetry",
    "Performance",
    "Profiling",
    "Load Testing",
    "JMeter",
    "Gatling",
    "Artillery",
    "QA",
    "Quality Assurance",
    "Test Automation",
    "Selenium",
    "Cypress",
    "Playwright",
    "Puppeteer",
    "Mockito",
    "JUnit",
    "NUnit",
    "xUnit",
    "Jest",
    "Mocha",
    "Chai",
    "Enzyme",
    "Testing Library",
    "Vitest",
    "SonarQube",
    "Static Analysis",
    "ESLint",
    "TSLint",
    "Prettier",
    "Code Coverage",
    "lcov",
    "Coverage",
    "Dependency Management",
    "npm",
    "yarn",
    "pnpm",
    "pnpm-workspace",
    "package.json",
    "Monorepo",
    "Lerna",
    "Nx",
    "Bazel",
    "Build Tools",
    "Make",
    "CMake",
    "Gradle",
    "Maven",
    "Visual Studio",
    "VS Code",
    "IntelliJ",
    "Eclipse",
    "Xcode",
    "Android Studio",
    "Debugger",
    "Profilers",
    "UML",
    "Design Patterns",
    "Agile",
    "Scrum",
    "Kanban",
    "CI",
    "DevOps",
    "SRE",
    "Site Reliability",
    "Infrastructure as Code",
    "Configuration Management",
    "Observability",
    "Blockchain",
    "Smart Contracts",
    "Solidity",
    "Web3",
    "IPFS",
    "Cryptography",
    "Ethereum",
    "Hyperledger",
    "AR/VR",
    "Unity",
    "Unreal Engine",
    "Game Development",
    "3D",
    "Computer Vision",
    "OpenCV",
    "Image Processing",
    "Signal Processing",
    "Robotics",
    "ROS",
    "IoT",
    "MQTT",
    "CoAP",
    "Edge Computing",
    "Server",
    "Backend",
    "Frontend",
    "Fullstack",
    "Architecture",
    "Microservices",
    "Monolith",
    "Event Driven",
    "CQRS",
    "ES (Event Sourcing)",
    "API Gateway",
    "Reverse Proxy",
    "Authentication",
    "Authorization",
    "Rate Limiting",
    "Caching",
    "CDN",
    "Message Queue",
    "Job Scheduling",
    "Cron",
    "Batch Processing",
    "ETL",
    "Data Warehousing",
    "Snowflake",
    "Redshift",
    "BigQuery",
    "Business Intelligence",
    "Tableau",
    "Power BI",
    "Looker",
    "Data Visualization",
    "UX",
    "UI",
    "Figma",
    "Sketch",
    "Adobe XD",
    "Design System",
    "Atomic Design",
    "Accessibility Testing",
    "Localization",
    "i18n",
    "l10n",
    "Continuous Delivery",
    "Release Management",
    "Feature Flags",
    "A/B Testing",
    "Observability",
    "Compliance",
    "GDPR",
    "HIPAA",
    "PCI-DSS",
    "Logging",
    "Backup",
    "Disaster Recovery",
    "High Availability",
    "Scalability",
    "Elasticity",
    "Cost Optimization",
    "Performance Tuning",
    "Refactoring",
    "Technical Debt",
    "Pair Programming",
    "Code Review",
    "Mentoring",
    "Onboarding",
    "Documentation",
    "Open Source",
    "Licensing",
    "Package Management",
    "Internationalization",
    "Localization",
    "ChatGPT",
    "AI",
    "ML Ops",
    "Model Deployment",
    "Edge AI",
    "Unity3D",
    "Unreal Engine",
    "Game Development",
    "3D",
    "Figma",
    "Sketch",
  ];

  @Get()
  getKeywords(): string[] {
    return this.KEYWORDS;
  }
}
